name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create short SHA
      run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      run: |
        docker build -t aimejeslyn/cicd-dummy:${{ env.SHORT_SHA }} .
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push aimejeslyn/cicd-dummy:${{ env.SHORT_SHA }}

    outputs:
      SHORT_SHA: ${{ env.SHORT_SHA }}

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: SSH into server and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USERNAME }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          docker pull aimejeslyn/cicd-dummy:${{ needs.build.outputs.SHORT_SHA }}
          docker rm -f cicd-dummy || true
          docker run -d -p 80:80 --name cicd-dummy aimejeslyn/cicd-dummy:${{ needs.build.outputs.SHORT_SHA }}
